# See https://docs.ansible.com/ansible/latest/dev_guide/collections_galaxy_meta.html

namespace: sd_hardy
name: logtail
version: 0.0.1
readme: README.md
authors:
  - Skyler Hardy (github.com/sd-hardy)
description: A collection to manage logtail.com sources
license_file: LICENSE
tags:
  - logtail
  - logging
repository: https://github.com/sd-hardy/ansible_collection_logtail
homepage: https://github.com/sd-hardy/ansible_collection_logtail
issues: https://github.com/sd-hardy/ansible_collection_logtail/issues
build_ignore:
# https://docs.ansible.com/ansible/devel/dev_guide/developing_collections_distributing.html#ignoring-files-and-folders
  - .gitignore
  - changelogs/.plugin-cache.yaml
